### ISSUE TITLE
the result is very high.

### ISSUE THREAD

**Issue by zhanghh2018** [conex-kge/ConEx#2]
I try to run the ConvE by using your code,but I find the result is very high,I suspect there is a problem with the code about the final evaluation index。And I run the Distmult ,the result is very high.

**Comment by conex-kge** [comment]
@zhanghh2018 thank you for your interest and remark. We based our implementation on https://github.com/ibalazevic/TuckER. Consequently, training protocol as well as evaluation evaluation protocols are identical which could be easily validated. That being said, if you any irregularities or bugs in the code, please let us know.

Please be reminded of the fact that using batch normalisation, 1vsAll scoring regime often lead better performances. You might want to take a look at the findings of [1].


[1] https://openreview.net/forum?id=BkxSmlBFvr
